[Definition]

failregex = ^<HOST> - .* "(GET|POST|HEAD) (/\.env|/\.git|/config|/backup|/vendor|/cgi-bin|/api/trpc)[^"]*" \d+
            ^<HOST> - .* "(GET|POST|HEAD) (/(wp-login\.php|xmlrpc\.php)|/wp-admin/?|/(phpmyadmin|pma)|/admin|/login|/signin)[^"]*" (403|404|444|500)

ignoreregex =